name: eslint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.3.x]

    steps:
      - uses: actions/checkout@v2
      - name: node.js[${{ matrix.node-version }}]
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --dev
      - run: echo "::add-matcher::.github/eslint-stylish.json"
      - run: yarn eslint -f compact src/**/*.ts