name: yarn jest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.3.x]

    steps:
      - uses: actions/checkout@v2
      - name: node.js[${{ matrix.node-version }}]
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --dev
      - run: echo "::add-matcher::.github/jest.json"
      - run: yarn -s jest --json --testLocationInResults | jq -e '.testResults | .[].assertionResults | map(select(.status != "passed")) | .[] | "jest:\(.location.line):\(.location.column):\(.failureMessages | .[])"'