name: yarn jest

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [15.3.x]

    steps:
      - uses: actions/checkout@v2
      - name: node.js [${{ matrix.node-version }}]
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --dev
      - name: enabling yarn problem matcher
        run: echo "::add-matcher::.github/jest.json"
      - name: yarn machine output
        run: yarn --silent jest --reporters=jest-github-actions-reporter